### ISSUE TITLE
graphs.forEach is not a function - 

### ISSUE THREAD

**Issue by wingsuitist** [amra/reveal-md-scripts#1]
I found two related issues in my setup:

1. the class name seems to be .language-mermaid not .mermaid
2. getElementsByClassName returns a HTMLCollection which doesn't support .forEach out of the box

The fix which works for me:
```js
    var graphs = Array.from(document.getElementsByClassName("language-mermaid"));
```

**Comment by maiermic** [comment]
@wingsuitist Which version of reveal-md are you using?

**Comment by wingsuitist** [comment]
Currently I'm using reveal-md 5.1.2 with this adapted reveal-mermaid.js script, as well as mermaid 8.10.1:

```js
mermaid.initialize({
    startOnLoad: false,
    theme: 'default',
    logLevel: 3,
});

Reveal.addEventListener('ready', event => asyncMermaidRender(event));

async function asyncMermaidRender(event) {
    var graphs = Array.from(document.getElementsByClassName("mermaid"));
    graphs.forEach((item, index) => {
        let graphCode = item.innerText.trim(); //trim() becase of gantt, class and git diagram
        let mermaidDiv = document.createElement('div');
        mermaidDiv.classList.add('mermaid');
        mermaidDiv.setAttribute("data-processed", "true");

        try {
            // item.innerText ignores html elements added by revealjs highlight plugin.
            mermaid.mermaidAPI.render('theGraph' + index, graphCode, function(svgCode) {
                mermaidDiv.innerHTML = svgCode;
            });

            let parentDiv = document.createElement('div');
            parentDiv.appendChild(mermaidDiv);
            item.parentNode.parentNode.insertBefore(parentDiv, item.parentNode);
            item.parentNode.remove();
        }
        catch(err) {
            console.log("Cannot render mermaid diagram " + index + "\n" + graphCode);
            console.log(err.message);
        }
    })
}
```

**Comment by maiermic** [comment]
@wingsuitist I'm using the same reveal-md version (5.1.2), but the [mermaid version](https://github.com/amra/reveal-md-scripts/blob/8802aecb5ad3231f082596ffa08abba08446f0ce/mermaidjs/test/lib/mermaid.min.js) of this repository. I don't know, which version number this is. However, I would expect that the class name depends only on reveal-md.

How do you define the code block of your graph?

    ```mermaid
    your graph code
    ```

or

    ```language-mermaid
    your graph code
    ```

**Comment by wingsuitist** [comment]
I use 

```md

```mermaid
xyz
```

```

**Comment by maiermic** [comment]
@wingsuitist Maybe I should have asked first: Is the source of your presentation/project public? Then I could have a look.

I guess, you fixed it (in your copy of the script) by changing the class name in

```js
var graphs = Array.from(document.getElementsByClassName("mermaid"));
```

to

```js
var graphs = Array.from(document.getElementsByClassName("language-mermaid"));
```

You could check both class names, but it would be good to know, why it is different. Maybe you can try, if you get a different class name, when you change your mermaid version to the [mermaid version](https://github.com/amra/reveal-md-scripts/blob/8802aecb5ad3231f082596ffa08abba08446f0ce/mermaidjs/test/lib/mermaid.min.js) of this repository.

---

PS: @amra is the maintainer, but I plan to contribute :wink:

**Comment by wingsuitist** [comment]
I think I updated the mermaid version due to some other mermaid issues partially resolved in the newest version (drawing arrows). I guess we could close this issue, and if you update your mermaid version in this repository to the newest one, you either have the same effect or it's something isolated in my environment.

**Comment by maciejmatczak** [comment]
For me it looks it's still actual.

https://github.com/amra/reveal-md-scripts/blob/bfc1d67df0a8aac36d018cd85e6e25ba3a2265f7/mermaidjs/reveal-mermaid.js#L10

... returns HTMLCollection, which doesn't have `.forEach` method:

![image](https://user-images.githubusercontent.com/1786383/234826973-065afdb8-d42e-4f76-97f8-24d064da24bf.png)

And it seems that's what @wingsuitist changed in a local snippet.

**Comment by wingsuitist** [comment]
@maciejmatczak This is the script I use to inject it:

```js
mermaid.initialize({
    startOnLoad: false,
    theme: 'default',
    logLevel: 3,
});

Reveal.addEventListener('ready', event => asyncMermaidRender(event));

async function asyncMermaidRender(event) {
    var graphs = Array.from(document.getElementsByClassName("mermaid"));
    graphs.forEach((item, index) => {
        let graphCode = item.innerText.trim(); //trim() becase of gantt, class and git diagram
        let mermaidDiv = document.createElement('div');
        mermaidDiv.classList.add('mermaid');
        mermaidDiv.setAttribute("data-processed", "true");

        try {
            // item.innerText ignores html elements added by revealjs highlight plugin.
            mermaid.mermaidAPI.render('theGraph' + index, graphCode, function(svgCode) {
                mermaidDiv.innerHTML = svgCode;
            });

            let parentDiv = document.createElement('div');
            parentDiv.appendChild(mermaidDiv);
            item.parentNode.parentNode.insertBefore(parentDiv, item.parentNode);
            item.parentNode.remove();
        }
        catch(err) {
            console.log("Cannot render mermaid diagram " + index + "\n" + graphCode);
            console.log(err.message);
        }
    })
}

```
