### ISSUE TITLE
Fails to render content inside of fragments

### ISSUE THREAD

**Issue by khaled** [amra/reveal-md-scripts#3]
Example:

````
<span class="fragment fade-up">

```mermaid
graph TD;
   input-A-->recipe;
   input-B-->recipe;
   input-C-->recipe;
   recipe-->output;
```

</span>
````

The reason is that `innerText` is being used, which only returns visible content:
https://github.com/amra/reveal-md-scripts/blob/3825cc01a87a9b658f9c1b9e5a73c780975446fe/mermaidjs/reveal-mermaid.js#L12

If the content is not (yet) visible, you get an empty string, and the graph does not render.  Instead you get a parsing error in the web console.

Changing `innerText` to `textContent` seems to resolve the problem.

**Comment by amra** [comment]
Thanks for the nice fix 👍
